version: '3.8'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2024-05-01T01-11-10Z
  command: server --address ":${MINIO_PORT}" --console-address ":${CONSOLE_PORT}" http://minio{1...4}/data{1...2}
  expose:
    - '${MINIO_PORT}'
    - '${CONSOLE_PORT}'
  environment:
    MINIO_ROOT_USER: minioadmin
    MINIO_ROOT_PASSWORD: minioadmin
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - ./minio-volumes/data1-1:/data1
      - ./minio-volumes/data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - ./minio-volumes/data2-1:/data1
      - ./minio-volumes/data2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - ./minio-volumes/data3-1:/data1
      - ./minio-volumes/data3-2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - ./minio-volumes/data4-1:/data1
      - ./minio-volumes/data4-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/templates/nginx.conf.template:ro
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
      MINIO_PORT: ${MINIO_PORT}
      CONSOLE_PORT: ${CONSOLE_PORT}
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
      - "${CONSOLE_PORT}:${CONSOLE_PORT}"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4