spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.hibernate.ddl-auto=create
spring.batch.job.enabled=false
aril.batch.table-prefix=BATCH_
aril.batch.active-module=thor_host
#spring.batch.jdbc.initialize-schema=always
#spring.batch.jdbc.platform=h2

# Minio Properties
spring.minio.url=http://127.0.0.1:9005
spring.minio.bucket=aril-bucket
spring.minio.access-key=jTBMDDQDBvh46ZoA5JzF
spring.minio.secret-key=VOpvFtt8uLTr63j42TDcWLoJYNXmY99Cjhs4H3fz

# Kafka Properties
aril.kafka.oauth.host=http://localhost:8080
aril.kafka.oauth.realm=aril
aril.kafka.oauth.token-uri=${aril.kafka.oauth.host}/realms/${aril.kafka.oauth.realm}/protocol/openid-connect/token
aril.kafka.oauth.bootstrap-servers=localhost:19092,localhost:19093,localhost:19094
aril.kafka.oauth.username-claim=preferred_username
aril.kafka.oauth.client-id=thor
aril.kafka.oauth.client-secret=thor-secret
logging.level.org.apache.kafka=warn
aril.kafka.listener.auto-startup=false
aril.kafka.listener.concurrency=3

# Idempotent Properties
spring.data.redis.password=redis_password_2024
spring.data.redis.username=default
spring.data.redis.sentinel.master=aril_master
spring.data.redis.sentinel.nodes=127.0.0.1:18379,127.0.0.1:19379,127.0.0.1:20379
aril.redis.client.enable-redisson-mode=true
aril.idempotent.mode=redis